# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "XXI. Türkiye'de İnternet Konferansı"
email: ""
description: "3-5 Kasım 2016,TED Üniversitesi"
baseurl: "/zeppelin"
url: "http://codescu.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "codescu.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "TEDU"
organizerAlternateName: "TED Üniversitesi"
organizerDescription: ""
organizerEmail: ""
organizerLogo: ""
organizerLink: "http://tedu.edu.tr/"

# Head
metaKeywords: "event, internet, ankara, türkiye, etkinlik, siber"
twitterAccount: "@inettrinet"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://openconf.inet-tr.org.tr/openconf.php"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Anasayfa"}
 - {permalink: "/blog/call-for-papers", text: "Çağrı"}
# - {permalink: "/schedule/", text: "Program"}
 #- {permalink: "/speakers/", text: "Konuşmacılar"}
 - {permalink: "/blog/kurullar", text: "Kurullar"}
 - {permalink: "/#partners", text: "Sponsorlar"}
# - {permalink: "/logistics/", text: "Ulaşım"}
 - {permalink: "/contact/", text: "İletİşİm"}
bottomNavigationLinks:
 - {link: "http://openconf.inet-tr.org.tr/openconf.php", text: "Konuşmacı Olun"}
rightNavigationButtons:
 - {link: "http://openconf.inet-tr.org.tr/openconf.php", text: "Konuşmacı Olun"}

# Hero Block
heroImage: "anit2.jpg"
heroTitle: "XXI. Türkiye'de İnternet Konferansı TEDÜ Ankara 2016"
eventDate: "3-5 Kasım 2016"
typeoutTextValues: '"", "TEDÜ", "Ankara"'
typeoutFallback: "TED Üniversitesi Ankara"
heroButtons:
 - {link: "http://openconf.inet-tr.org.tr/openconf.php", text: "Konuşmacı Ol"}
 - {permalink: "/#tickets", text: "Kayıt Ol"}

# About Block
aboutTitle: "Etkinlik"
aboutBlock:
 - {title: "Konferans", image: "conference.jpg", text: "" }
 - {title: "Çalıştaylar", image: "workshop.jpg", text: "" }
 #- {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "500", specialCharacter: "+", info: "katılımcı", detail: "Türkiye'nin her yerinden"}
 - {count: "72", specialCharacter: "+", info: "saat", detail: "Türkiye'de İnternet"}
 - {count: "20", specialCharacter: "+", info: "konuşmacı", detail: "Çeşitli Alanlarda "}
 - {count: "4", specialCharacter: "", info: "paralel oturum", detail: "+ Fuar Alanı"}

# Latest News Block
latestNewsTitle: "Son Güncellemeler"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 0

# Location Block
locationBlockTitle: "Lokasyon"
eventLocationName: "Konferans Alanı"
eventLocationLink: "http://www.tedu.edu.tr/tr/main/iletisim"
eventStreetAddress: "TED Üniversitesi, Ziya Gökalp Caddesi No.48"
eventAddressLocality: "Kolej"
eventAddressLocalityRegion: "Ankara"
eventPostalCode: "06420"
eventAddressCountry: "Türkiye"
eventStartTime: "2016-10-03T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-05T20:00"
eventPlaceCoordinates: "39.9238168,32.8612121"
mapCenterCoordinates: "39.9238168,32.8612121"
mapMobileCenterCoordinates: "39.9238168,32.8612121"

# Venue Block
venueBlockTitle: "Mekan"
venueBigImage: "tedu1.jpg"
venueSmallImage1: "tedu1.jpg"
venueSmallImage2: "tedu1.jpg"
venueSmallImage3: "tedu1.jpg"
venueTitle: "TED Üniversitesi Yeni Kampüs"
venueFeatures: ["4 Ayrı Salon", "Şehir merkezinde"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Neler oluyor?"
twitterHashTag: "inettr2016"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organize Edenler"
partnersTitle: "Sponsorlar"
partnersC4sponsorsButton: "Sponsor Ol"

# Tickets Block
ticketsTitle: "Kayıt"
ticketsInfo: ""
ticketsOffers:
 -
  name: "Bilet"
  price: "Ücretsiz"
  priceCurrency: ""
  ticketsNumber: "150"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Kayıt Ol"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2016-10-03T10:00"
  validThrough: "2016-10-05T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Linkler"
  links:
   - {link: "http://inet-tr.org.tr/", text: "inet-tr"}

# Blog
blogTitle: "Son Haberler"
blogCommentsEnabled: true
discusShortName: "inettr2016"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Hakkımızda"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Ulaşım"
findWayDistance: "Mesafe"
findWayDriving: "Araba"
findWayWalking: "Yürüme"
findWayBicycling: "Bisiklet"
findWayTransit: "Toplu Taşıma"
findWayFindFlight: "Uçak Bul"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Ankara"
directionDetailsCards:
 - {title: "Havaalanı", information: "Havaalanından kalkan BelkoAir otobusleri ile Kızılay'a geldikten sonra, taksi veya metro kullanarak veya yürüyerek etkinlik alanına ulaşabilirsiniz."}
 - {title: "Toplu Taşıma", information: "Ankaray Metrosu Kolej Metrosu'ndan çıkarak etkinlik alanına ulaşabilirsiniz."}
directionDetailsWideCards:
 -
  title: "Oteller"
  subCards:
   -
    title: ""
    links:
     - {link: "https://albahotels.com.tr/Home/Alba_Ankara_Hotel", text: "ALBA ANKARA HOTEL"}
     - {link: "http://hoteltunali.com.tr/index_en.php", text: "Hotel Tunali"}
     - {link: "http://www.anemonhotels.com/", text: "Hotel Anemon"}
   -
    title: ""
    links:
     - {link: "http://www.besthotel.com.tr/", text: "Hotel Best"}
     - {link: "http://hiankara.com/", text: "Holiday Inn Kavaklidere - Ankara"}
   -
-
